### ISSUE TITLE
Nano or STM32 - compatible boards?

### ISSUE THREAD

**Issue by luciust** [Andy4495/HCMS39xx#2]
Which board did you test that with? Seems that Arduino IDe 1.8.5 or latest 2.0.1 has issues with Arduino Nano, while it compiles OK for STM32 (bluepill boards)

**Comment by Andy4495** [comment]
I have tested on Arduino Uno, a 328-based board like the Nano. I'm not getting any errors when I compile the example sketches for Arduino Nano with IDE 2.0.1.

Please paste specific errors you are seeing (actually, the entire compiler output) and I can take a look.

**Comment by luciust** [comment]
Thanks, I'll doublke check my setup first, then get back with detail - if the problem persists

**Comment by luciust** [comment]
Nah, fixed - my bad. Compiles OK!
