### ISSUE TITLE
[SOLVED] Wiring schematics, Example 1 and Arduino Uno/Nano

### ISSUE THREAD

**Issue by luciust** [Andy4495/HCMS39xx#3]
Hey,
trying to get it running with Arduino Uno and Nano, HCMS-3904, Example 1 - seems from the example that wiring shold be:

Ardu      HCMS-3904
+3,3V - VLED (Pin 3) - that is comming from PSU
PIN 6 -  Data In (Pin 4)
PIN 7 -  RS (Pin 5)
PIN 8 -  CLCK (Pin 6)
PIN 9 -  CE (Pin 7)
PIN 10 - RESET (Pin 12)
GND    - Pin 8 & 9
+3,3V -  Pin 10 & 11 - that is comming to from PSU

Correct?

Serial ports on Ardu spits out the procedure for all example steps, yet the scope doesn't show any clock running on PIN 8 of Ardu, and the HCMS is not working.

What am I doint wrong here?

**Comment by Andy4495** [comment]
It seems like your connections are correct. I glanced at my code again and I don't see anything wrong. 

I don't have access to my setup right now and won't be able to test it until later Sunday. Ince I can try it in my setup I'll let you know if I find anything. 

One possible thing to check is if you are using an Uno at 5 volts, make sure you are also powering the LED at 5 volts. But I don't see how that would affect the CLK signal.

**Comment by luciust** [comment]
Yeah, I assumed that 3,3V should be used, but since datasheet says it is 5V tollerant I'll try that.

**Comment by luciust** [comment]
Got partial operation! The Reset input on the display needs to be HIGH (3,3V) and SEL + BLANK - need to be LOW... Investigating...

**Comment by Andy4495** [comment]
I tested both examples (unmodified) with an HCMS-3964 without any issues. 

I have it connected as follows: 

| Signal Name | Arduino | HCMS | 
|:---------------| :-------: | :---:|
| Dout              | NC       | 1 |
| OSC               | NC       | 2 |
| V_LED            | 5V       | 3 |
| Din                | 6         | 4 |
| RS                 | 7          | 5 |
| CLK               | 8          | 6 |
| CE                 | 9          | 7 |
| BLANK          | 10        | 8 |
| GND             | GND    | 9 |
| SEL               | 5V       | 10 |
| VLOGIC        | 5V       | 11 |
| RESET          | 5V       | 12 |

Here's a picture of my setup, hopefully it is clear enough to see the wiring layout: 

![IMG_4609](https://user-images.githubusercontent.com/13700150/200221362-de403545-f0fb-4a42-9c2d-70bce685c51a.JPG)

**Comment by luciust** [comment]
Thanks!

I've got 3904 not 3964 and all it does so far (either with original UNO or cheap NANO) - displays lines - full then dotted. 
Connections seem to be pretty much the same, but I need to check

![image](https://user-images.githubusercontent.com/30508311/200253903-98a8b5c2-c968-4dd8-9fd5-5d8daf56098f.png)

**Comment by Andy4495** [comment]
I can't quite tell from the picture, but there are a couple connections on your setup that appear to be different than mine: 

- HCMS pin 8 should go to Arduino pin 10 (looks like it is going to GND on your setup)
- HCMS pin 10 should go to 5V (looks like it is going to GND on your setup

How long are you letting the example 1 sketch run? The first 60 seconds or so of the sketch uses vertical and horizontal bars test various aspects of the display and library, including scrolling and dimming. It isn't towards the end of the sketch that it starts printing actual characters. 

If you watch the output from the Serial port you can see an explanation of each test as it is running. Try waiting it out through the end of the test run to see if you can see the characters. 

You can also try running example 2, as that scrolls all the characters in the character map.

**Comment by luciust** [comment]
Solved! Your suggestions on the pin 8 and 10 - helped! It works now, goes through full circle: 
![image](https://user-images.githubusercontent.com/30508311/200430926-d63bb03f-00be-4a2b-be34-ccd10c537bc2.png)

**Comment by Andy4495** [comment]
Great! Glad you were able to get it to work.
